services:
  backend:
    build: ./backend
    image: amituliel1/backend:v1
    container_name: backend_c
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb_c:27017/note-taking-app

  frontend:
    build: ./frontend
    image: amituliel1/frontend:v1
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb_c
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  backend_node_modules:
  frontend_node_modules:
  mongodb_data: